[pytest]

#Detecta todos los archivos en pytest que comiencen con test_
python_files = test_*.py
python_functions = test_*

#Genera reporte en html con el estilo en el mismo html
addopts = -v --html=reports/reporte.html --self-contained-html



